language: bash
sudo: false
cache:
  directories:
      - $HOME/cachedir
install: git clone --depth 1 https://github.com/sstephenson/bats.git $HOME/bats
before_script:
  - "export LOCAL_CI_TESTS_CACHEDIR=$HOME/cachedir && mkdir -p $LOCAL_CI_TESTS_CACHEDIR"
  - "export LOCAL_CI_TESTS_GITDIR=$HOME/gitdir && git clone git://github.com/moodle/moodle $LOCAL_CI_TESTS_GITDIR"
script:
  - $HOME/bats/bin/bats tests

